# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xubuntu/Desktop/Engine3/ChoraEngine/dangeroustux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xubuntu/Desktop/Engine3/ChoraEngine/dangeroustux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xubuntu/Desktop/Engine3/ChoraEngine/dangeroustux/CMakeFiles /home/xubuntu/Desktop/Engine3/ChoraEngine/dangeroustux/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xubuntu/Desktop/Engine3/ChoraEngine/dangeroustux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DangerousTux

# Build rule for target.
DangerousTux: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DangerousTux
.PHONY : DangerousTux

# fast build rule for target.
DangerousTux/fast:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/build
.PHONY : DangerousTux/fast

src/dangerous_tux.o: src/dangerous_tux.cpp.o

.PHONY : src/dangerous_tux.o

# target to build an object file
src/dangerous_tux.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/dangerous_tux.cpp.o
.PHONY : src/dangerous_tux.cpp.o

src/dangerous_tux.i: src/dangerous_tux.cpp.i

.PHONY : src/dangerous_tux.i

# target to preprocess a source file
src/dangerous_tux.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/dangerous_tux.cpp.i
.PHONY : src/dangerous_tux.cpp.i

src/dangerous_tux.s: src/dangerous_tux.cpp.s

.PHONY : src/dangerous_tux.s

# target to generate assembly for a file
src/dangerous_tux.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/dangerous_tux.cpp.s
.PHONY : src/dangerous_tux.cpp.s

src/flyeralien.o: src/flyeralien.cpp.o

.PHONY : src/flyeralien.o

# target to build an object file
src/flyeralien.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/flyeralien.cpp.o
.PHONY : src/flyeralien.cpp.o

src/flyeralien.i: src/flyeralien.cpp.i

.PHONY : src/flyeralien.i

# target to preprocess a source file
src/flyeralien.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/flyeralien.cpp.i
.PHONY : src/flyeralien.cpp.i

src/flyeralien.s: src/flyeralien.cpp.s

.PHONY : src/flyeralien.s

# target to generate assembly for a file
src/flyeralien.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/flyeralien.cpp.s
.PHONY : src/flyeralien.cpp.s

src/gamecredits.o: src/gamecredits.cpp.o

.PHONY : src/gamecredits.o

# target to build an object file
src/gamecredits.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gamecredits.cpp.o
.PHONY : src/gamecredits.cpp.o

src/gamecredits.i: src/gamecredits.cpp.i

.PHONY : src/gamecredits.i

# target to preprocess a source file
src/gamecredits.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gamecredits.cpp.i
.PHONY : src/gamecredits.cpp.i

src/gamecredits.s: src/gamecredits.cpp.s

.PHONY : src/gamecredits.s

# target to generate assembly for a file
src/gamecredits.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gamecredits.cpp.s
.PHONY : src/gamecredits.cpp.s

src/gameentity.o: src/gameentity.cpp.o

.PHONY : src/gameentity.o

# target to build an object file
src/gameentity.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gameentity.cpp.o
.PHONY : src/gameentity.cpp.o

src/gameentity.i: src/gameentity.cpp.i

.PHONY : src/gameentity.i

# target to preprocess a source file
src/gameentity.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gameentity.cpp.i
.PHONY : src/gameentity.cpp.i

src/gameentity.s: src/gameentity.cpp.s

.PHONY : src/gameentity.s

# target to generate assembly for a file
src/gameentity.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gameentity.cpp.s
.PHONY : src/gameentity.cpp.s

src/gameevent_manager.o: src/gameevent_manager.cpp.o

.PHONY : src/gameevent_manager.o

# target to build an object file
src/gameevent_manager.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gameevent_manager.cpp.o
.PHONY : src/gameevent_manager.cpp.o

src/gameevent_manager.i: src/gameevent_manager.cpp.i

.PHONY : src/gameevent_manager.i

# target to preprocess a source file
src/gameevent_manager.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gameevent_manager.cpp.i
.PHONY : src/gameevent_manager.cpp.i

src/gameevent_manager.s: src/gameevent_manager.cpp.s

.PHONY : src/gameevent_manager.s

# target to generate assembly for a file
src/gameevent_manager.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gameevent_manager.cpp.s
.PHONY : src/gameevent_manager.cpp.s

src/gameintroduction.o: src/gameintroduction.cpp.o

.PHONY : src/gameintroduction.o

# target to build an object file
src/gameintroduction.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gameintroduction.cpp.o
.PHONY : src/gameintroduction.cpp.o

src/gameintroduction.i: src/gameintroduction.cpp.i

.PHONY : src/gameintroduction.i

# target to preprocess a source file
src/gameintroduction.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gameintroduction.cpp.i
.PHONY : src/gameintroduction.cpp.i

src/gameintroduction.s: src/gameintroduction.cpp.s

.PHONY : src/gameintroduction.s

# target to generate assembly for a file
src/gameintroduction.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gameintroduction.cpp.s
.PHONY : src/gameintroduction.cpp.s

src/gamemenu.o: src/gamemenu.cpp.o

.PHONY : src/gamemenu.o

# target to build an object file
src/gamemenu.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gamemenu.cpp.o
.PHONY : src/gamemenu.cpp.o

src/gamemenu.i: src/gamemenu.cpp.i

.PHONY : src/gamemenu.i

# target to preprocess a source file
src/gamemenu.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gamemenu.cpp.i
.PHONY : src/gamemenu.cpp.i

src/gamemenu.s: src/gamemenu.cpp.s

.PHONY : src/gamemenu.s

# target to generate assembly for a file
src/gamemenu.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gamemenu.cpp.s
.PHONY : src/gamemenu.cpp.s

src/gameover.o: src/gameover.cpp.o

.PHONY : src/gameover.o

# target to build an object file
src/gameover.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gameover.cpp.o
.PHONY : src/gameover.cpp.o

src/gameover.i: src/gameover.cpp.i

.PHONY : src/gameover.i

# target to preprocess a source file
src/gameover.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gameover.cpp.i
.PHONY : src/gameover.cpp.i

src/gameover.s: src/gameover.cpp.s

.PHONY : src/gameover.s

# target to generate assembly for a file
src/gameover.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gameover.cpp.s
.PHONY : src/gameover.cpp.s

src/gamescreen.o: src/gamescreen.cpp.o

.PHONY : src/gamescreen.o

# target to build an object file
src/gamescreen.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gamescreen.cpp.o
.PHONY : src/gamescreen.cpp.o

src/gamescreen.i: src/gamescreen.cpp.i

.PHONY : src/gamescreen.i

# target to preprocess a source file
src/gamescreen.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gamescreen.cpp.i
.PHONY : src/gamescreen.cpp.i

src/gamescreen.s: src/gamescreen.cpp.s

.PHONY : src/gamescreen.s

# target to generate assembly for a file
src/gamescreen.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gamescreen.cpp.s
.PHONY : src/gamescreen.cpp.s

src/gamesignal.o: src/gamesignal.cpp.o

.PHONY : src/gamesignal.o

# target to build an object file
src/gamesignal.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gamesignal.cpp.o
.PHONY : src/gamesignal.cpp.o

src/gamesignal.i: src/gamesignal.cpp.i

.PHONY : src/gamesignal.i

# target to preprocess a source file
src/gamesignal.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gamesignal.cpp.i
.PHONY : src/gamesignal.cpp.i

src/gamesignal.s: src/gamesignal.cpp.s

.PHONY : src/gamesignal.s

# target to generate assembly for a file
src/gamesignal.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gamesignal.cpp.s
.PHONY : src/gamesignal.cpp.s

src/gametitle.o: src/gametitle.cpp.o

.PHONY : src/gametitle.o

# target to build an object file
src/gametitle.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gametitle.cpp.o
.PHONY : src/gametitle.cpp.o

src/gametitle.i: src/gametitle.cpp.i

.PHONY : src/gametitle.i

# target to preprocess a source file
src/gametitle.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gametitle.cpp.i
.PHONY : src/gametitle.cpp.i

src/gametitle.s: src/gametitle.cpp.s

.PHONY : src/gametitle.s

# target to generate assembly for a file
src/gametitle.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gametitle.cpp.s
.PHONY : src/gametitle.cpp.s

src/gametransition.o: src/gametransition.cpp.o

.PHONY : src/gametransition.o

# target to build an object file
src/gametransition.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gametransition.cpp.o
.PHONY : src/gametransition.cpp.o

src/gametransition.i: src/gametransition.cpp.i

.PHONY : src/gametransition.i

# target to preprocess a source file
src/gametransition.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gametransition.cpp.i
.PHONY : src/gametransition.cpp.i

src/gametransition.s: src/gametransition.cpp.s

.PHONY : src/gametransition.s

# target to generate assembly for a file
src/gametransition.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gametransition.cpp.s
.PHONY : src/gametransition.cpp.s

src/gun.o: src/gun.cpp.o

.PHONY : src/gun.o

# target to build an object file
src/gun.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gun.cpp.o
.PHONY : src/gun.cpp.o

src/gun.i: src/gun.cpp.i

.PHONY : src/gun.i

# target to preprocess a source file
src/gun.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gun.cpp.i
.PHONY : src/gun.cpp.i

src/gun.s: src/gun.cpp.s

.PHONY : src/gun.s

# target to generate assembly for a file
src/gun.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gun.cpp.s
.PHONY : src/gun.cpp.s

src/gyroalien.o: src/gyroalien.cpp.o

.PHONY : src/gyroalien.o

# target to build an object file
src/gyroalien.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gyroalien.cpp.o
.PHONY : src/gyroalien.cpp.o

src/gyroalien.i: src/gyroalien.cpp.i

.PHONY : src/gyroalien.i

# target to preprocess a source file
src/gyroalien.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gyroalien.cpp.i
.PHONY : src/gyroalien.cpp.i

src/gyroalien.s: src/gyroalien.cpp.s

.PHONY : src/gyroalien.s

# target to generate assembly for a file
src/gyroalien.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/gyroalien.cpp.s
.PHONY : src/gyroalien.cpp.s

src/highscore.o: src/highscore.cpp.o

.PHONY : src/highscore.o

# target to build an object file
src/highscore.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/highscore.cpp.o
.PHONY : src/highscore.cpp.o

src/highscore.i: src/highscore.cpp.i

.PHONY : src/highscore.i

# target to preprocess a source file
src/highscore.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/highscore.cpp.i
.PHONY : src/highscore.cpp.i

src/highscore.s: src/highscore.cpp.s

.PHONY : src/highscore.s

# target to generate assembly for a file
src/highscore.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/highscore.cpp.s
.PHONY : src/highscore.cpp.s

src/jetpack.o: src/jetpack.cpp.o

.PHONY : src/jetpack.o

# target to build an object file
src/jetpack.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/jetpack.cpp.o
.PHONY : src/jetpack.cpp.o

src/jetpack.i: src/jetpack.cpp.i

.PHONY : src/jetpack.i

# target to preprocess a source file
src/jetpack.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/jetpack.cpp.i
.PHONY : src/jetpack.cpp.i

src/jetpack.s: src/jetpack.cpp.s

.PHONY : src/jetpack.s

# target to generate assembly for a file
src/jetpack.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/jetpack.cpp.s
.PHONY : src/jetpack.cpp.s

src/level.o: src/level.cpp.o

.PHONY : src/level.o

# target to build an object file
src/level.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/level.cpp.o
.PHONY : src/level.cpp.o

src/level.i: src/level.cpp.i

.PHONY : src/level.i

# target to preprocess a source file
src/level.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/level.cpp.i
.PHONY : src/level.cpp.i

src/level.s: src/level.cpp.s

.PHONY : src/level.s

# target to generate assembly for a file
src/level.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/level.cpp.s
.PHONY : src/level.cpp.s

src/leveleditor.o: src/leveleditor.cpp.o

.PHONY : src/leveleditor.o

# target to build an object file
src/leveleditor.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/leveleditor.cpp.o
.PHONY : src/leveleditor.cpp.o

src/leveleditor.i: src/leveleditor.cpp.i

.PHONY : src/leveleditor.i

# target to preprocess a source file
src/leveleditor.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/leveleditor.cpp.i
.PHONY : src/leveleditor.cpp.i

src/leveleditor.s: src/leveleditor.cpp.s

.PHONY : src/leveleditor.s

# target to generate assembly for a file
src/leveleditor.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/leveleditor.cpp.s
.PHONY : src/leveleditor.cpp.s

src/player.o: src/player.cpp.o

.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i

.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s

.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/save.o: src/save.cpp.o

.PHONY : src/save.o

# target to build an object file
src/save.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/save.cpp.o
.PHONY : src/save.cpp.o

src/save.i: src/save.cpp.i

.PHONY : src/save.i

# target to preprocess a source file
src/save.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/save.cpp.i
.PHONY : src/save.cpp.i

src/save.s: src/save.cpp.s

.PHONY : src/save.s

# target to generate assembly for a file
src/save.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/save.cpp.s
.PHONY : src/save.cpp.s

src/score.o: src/score.cpp.o

.PHONY : src/score.o

# target to build an object file
src/score.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/score.cpp.o
.PHONY : src/score.cpp.o

src/score.i: src/score.cpp.i

.PHONY : src/score.i

# target to preprocess a source file
src/score.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/score.cpp.i
.PHONY : src/score.cpp.i

src/score.s: src/score.cpp.s

.PHONY : src/score.s

# target to generate assembly for a file
src/score.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/score.cpp.s
.PHONY : src/score.cpp.s

src/walkeralien.o: src/walkeralien.cpp.o

.PHONY : src/walkeralien.o

# target to build an object file
src/walkeralien.cpp.o:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/walkeralien.cpp.o
.PHONY : src/walkeralien.cpp.o

src/walkeralien.i: src/walkeralien.cpp.i

.PHONY : src/walkeralien.i

# target to preprocess a source file
src/walkeralien.cpp.i:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/walkeralien.cpp.i
.PHONY : src/walkeralien.cpp.i

src/walkeralien.s: src/walkeralien.cpp.s

.PHONY : src/walkeralien.s

# target to generate assembly for a file
src/walkeralien.cpp.s:
	$(MAKE) -f CMakeFiles/DangerousTux.dir/build.make CMakeFiles/DangerousTux.dir/src/walkeralien.cpp.s
.PHONY : src/walkeralien.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... DangerousTux"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... src/dangerous_tux.o"
	@echo "... src/dangerous_tux.i"
	@echo "... src/dangerous_tux.s"
	@echo "... src/flyeralien.o"
	@echo "... src/flyeralien.i"
	@echo "... src/flyeralien.s"
	@echo "... src/gamecredits.o"
	@echo "... src/gamecredits.i"
	@echo "... src/gamecredits.s"
	@echo "... src/gameentity.o"
	@echo "... src/gameentity.i"
	@echo "... src/gameentity.s"
	@echo "... src/gameevent_manager.o"
	@echo "... src/gameevent_manager.i"
	@echo "... src/gameevent_manager.s"
	@echo "... src/gameintroduction.o"
	@echo "... src/gameintroduction.i"
	@echo "... src/gameintroduction.s"
	@echo "... src/gamemenu.o"
	@echo "... src/gamemenu.i"
	@echo "... src/gamemenu.s"
	@echo "... src/gameover.o"
	@echo "... src/gameover.i"
	@echo "... src/gameover.s"
	@echo "... src/gamescreen.o"
	@echo "... src/gamescreen.i"
	@echo "... src/gamescreen.s"
	@echo "... src/gamesignal.o"
	@echo "... src/gamesignal.i"
	@echo "... src/gamesignal.s"
	@echo "... src/gametitle.o"
	@echo "... src/gametitle.i"
	@echo "... src/gametitle.s"
	@echo "... src/gametransition.o"
	@echo "... src/gametransition.i"
	@echo "... src/gametransition.s"
	@echo "... src/gun.o"
	@echo "... src/gun.i"
	@echo "... src/gun.s"
	@echo "... src/gyroalien.o"
	@echo "... src/gyroalien.i"
	@echo "... src/gyroalien.s"
	@echo "... src/highscore.o"
	@echo "... src/highscore.i"
	@echo "... src/highscore.s"
	@echo "... src/jetpack.o"
	@echo "... src/jetpack.i"
	@echo "... src/jetpack.s"
	@echo "... src/level.o"
	@echo "... src/level.i"
	@echo "... src/level.s"
	@echo "... src/leveleditor.o"
	@echo "... src/leveleditor.i"
	@echo "... src/leveleditor.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/save.o"
	@echo "... src/save.i"
	@echo "... src/save.s"
	@echo "... src/score.o"
	@echo "... src/score.i"
	@echo "... src/score.s"
	@echo "... src/walkeralien.o"
	@echo "... src/walkeralien.i"
	@echo "... src/walkeralien.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

